In [21]:
# Import libraries
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split


# For showing all the the Data Frame columns
%matplotlib inline
pd.set_option('display.max_columns', None)

In [22]:
# Load king_country_dataset
df = pd.read_csv('king_ country_ houses_aa.csv')
df.head()

,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
0,7129300520,20141013T000000,221900.0,3,1.00,1180,5650,1.0,0,0,3,7,1180,0,1955,0,98178,47.5112,-122.257,1340,5650
1,6414100192,20141209T000000,538000.0,3,2.25,2570,7242,2.0,0,0,3,7,2170,400,1951,1991,98125,47.7210,-122.319,1690,7639
2,5631500400,20150225T000000,180000.0,2,1.00,770,10000,1.0,0,0,3,6,770,0,1933,0,98028,47.7379,-122.233,2720,8062
3,2487200875,20141209T000000,604000.0,4,3.00,1960,5000,1.0,0,0,5,7,1050,910,1965,0,98136,47.5208,-122.393,1360,5000
4,1954400510,20150218T000000,510000.0,3,2.00,1680,8080,1.0,0,0,3,8,1680,0,1987,0,98074,47.6168,-122.045,1800,7503

# Data inspection and cleaning

In this dataset we have to predict the sales price of houses in King County, Seattle. It includes homes sold between May 2014 and May 2015.   

The dataset cantains 20 house features plus the price, along with 21613 observations.  

The description for the 20 features is given below:  

id :- It is the unique numeric number assigned to each house being sold.  
date :- It is the date on which the house was sold out.  
price:- It is the price of house which we have to predict so this is our target variable and aprat from it are our features.  
bedrooms :- It determines number of bedrooms in a house.  
bathrooms :- It determines number of bathrooms in a bedroom of a house.  
sqft_living :- It is the measurement variable which determines the measurement of house in square foot.  
sqft_lot : It is also the measurement variable which determines square foot of the lot.  
floors: It determines total floors means levels of house.  
waterfront : This feature determines whether a house has a view to waterfront 0 means no 1 means yes.  
view : This feature determines whether a house has been viewed or not 0 means no 1 means yes.  
condition : It determines the overall condition of a house on a scale of 1 to 5.  
grade : It determines the overall grade given to the housing unit, based on King County grading system on a scale of 1 to 11   
sqft_above : It determines square footage of house apart from basement.  
sqft_basement : It determines square footage of the basement of the house.  
yr_built : It detrmines the date of building of the house.  
yr_renovated : It detrmines year of renovation of house.  
zipcode : It determines the zipcode of the location of the house.  
lat : It determines the latitude of the location of the house.  
long : It determines the longitude of the location of the house.  
sqft_living15 : Living room area in 2015(implies-- some renovations)  
sqft_lot15 : lotSize area in 2015(implies-- some renovations)

In [23]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21613 entries, 0 to 21612
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   id             21613 non-null  int64
 1   date           21613 non-null  object
 2   price          21613 non-null  float64
 3   bedrooms       21613 non-null  int64
 4   bathrooms      21613 non-null  float64
 5   sqft_living    21613 non-null  int64
 6   sqft_lot       21613 non-null  int64
 7   floors         21613 non-null  float64
 8   waterfront     21613 non-null  int64
 9   view           21613 non-null  int64
 10  condition      21613 non-null  int64
 11  grade          21613 non-null  int64
 12  sqft_above     21613 non-null  int64
 13  sqft_basement  21613 non-null  int64
 14  yr_built       21613 non-null  int64
 15  yr_renovated   21613 non-null  int64
 16  zipcode        21613 non-null  int64
 17  lat            21613 non-null  float64
 18  long           21613 non-null  float64
 19  sqft_living15  21613 non-null  int64
 20  sqft_lot15     21613 non-null  int64
dtypes: float64(5), int64(15), object(1)
memory usage: 3.5+ MB

In [24]:
df.nunique()

id               21436
date               372
price             4028
bedrooms            13
bathrooms           30
sqft_living       1038
sqft_lot          9782
floors               6
waterfront           2
view                 5
condition            5
grade               12
sqft_above         946
sqft_basement      306
yr_built           116
yr_renovated        70
zipcode             70
lat               5034
long               752
sqft_living15      777
sqft_lot15        8689
dtype: int64

In [25]:
# Looking for missing values
df.isnull().sum()

id               0
date             0
price            0
bedrooms         0
bathrooms        0
sqft_living      0
sqft_lot         0
floors           0
waterfront       0
view             0
condition        0
grade            0
sqft_above       0
sqft_basement    0
yr_built         0
yr_renovated     0
zipcode          0
lat              0
long             0
sqft_living15    0
sqft_lot15       0
dtype: int64

In [26]:
# Looking for duplicated rows
df.duplicated().sum()

np.int64(0)

In [27]:
# Looking for values spcaed
df.eq(" ").sum()

id               0
date             0
price            0
bedrooms         0
bathrooms        0
sqft_living      0
sqft_lot         0
floors           0
waterfront       0
view             0
condition        0
grade            0
sqft_above       0
sqft_basement    0
yr_built         0
yr_renovated     0
zipcode          0
lat              0
long             0
sqft_living15    0
sqft_lot15       0
dtype: int64

In [28]:
# Checking if there are duplicated columns
duplicated_cols = df.T.duplicated()
df.columns[duplicated_cols]

Index([], dtype='object')

In [29]:
df['yr_renovated'].value_counts()

yr_renovated
0       20699
2014       91
2013       37
2003       36
2005       35
        ...
1948        1
1951        1
1959        1
1934        1
1944        1
Name: count, Length: 70, dtype: int64

In [30]:
df.date.dtype

dtype('O')

In [31]:
# Change type of the column 'date'
df.date = pd.to_datetime(df.date)

In [32]:
# Creating columns with year, month day
df['year-sold'] = df.date.dt.year
df['month-sold'] = df.date.dt.month
df['day-sold'] = df.date.dt.day

# Baseline

Define target and features

In [40]:
X = df.drop(['id', 'price', 'date'], axis=1) # Features
y = df['price'] # Target

In [41]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=.2, random_state=42)

In [42]:
from sklearn.linear_model import LinearRegression
 # Create the Linear Regression estimator
lm = LinearRegression()

# Perform the fitting
lm.fit(X_train, y_train)

LinearRegression()

In [43]:
y_train_pred = lm.predict(X_train)
y_test_pred = lm.predict(X_test)

In [48]:

import statsmodels.api as sm
est = sm.OLS(y_train, X_train) # Creates an object OLS estimator
est = est.fit()
est.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                                 OLS Regression Results
=======================================================================================
Dep. Variable:                  price   R-squared (uncentered):                   0.907
Model:                            OLS   Adj. R-squared (uncentered):              0.907
Method:                 Least Squares   F-statistic:                              8390.
Date:                Thu, 12 Feb 2026   Prob (F-statistic):                        0.00
Time:                        11:34:04   Log-Likelihood:                     -2.3540e+05
No. Observations:               17290   AIC:                                  4.708e+05
Df Residuals:                   17270   BIC:                                  4.710e+05
Df Model:                          20
Covariance Type:            nonrobust
=================================================================================
                    coef    std err          t      P>|t|      [0.025      0.975]
---------------------------------------------------------------------------------
bedrooms      -3.476e+04   2079.864    -16.712      0.000   -3.88e+04   -3.07e+04
bathrooms      4.466e+04   3602.302     12.396      0.000    3.76e+04    5.17e+04
sqft_living     109.3341      2.527     43.274      0.000     104.382     114.286
sqft_lot          0.0838      0.058      1.452      0.146      -0.029       0.197
floors         8455.6227   3951.154      2.140      0.032     710.960    1.62e+04
waterfront     5.627e+05   1.95e+04     28.886      0.000    5.25e+05    6.01e+05
view           5.391e+04   2354.913     22.893      0.000    4.93e+04    5.85e+04
condition       2.43e+04   2577.973      9.427      0.000    1.92e+04    2.94e+04
grade          9.492e+04   2369.229     40.065      0.000    9.03e+04    9.96e+04
sqft_above       69.6635      2.483     28.057      0.000      64.797      74.530
sqft_basement    39.6706      2.934     13.522      0.000      33.920      45.421
yr_built      -2730.2383     79.621    -34.291      0.000   -2886.303   -2574.173
yr_renovated     20.4134      4.052      5.037      0.000      12.470      28.357
zipcode        -609.3511     35.208    -17.307      0.000    -678.363    -540.339
lat            5.974e+05   1.18e+04     50.417      0.000    5.74e+05    6.21e+05
long           -1.93e+05   1.46e+04    -13.237      0.000   -2.22e+05   -1.64e+05
sqft_living15    19.8323      3.798      5.222      0.000      12.388      27.277
sqft_lot15       -0.3318      0.082     -4.061      0.000      -0.492      -0.172
year-sold      6200.7856   1532.804      4.045      0.000    3196.335    9205.237
month-sold    -2394.8960    517.294     -4.630      0.000   -3408.845   -1380.947
day-sold       -440.1101    174.844     -2.517      0.012    -782.822     -97.398
==============================================================================
Omnibus:                    14988.404   Durbin-Watson:                   1.995
Prob(Omnibus):                  0.000   Jarque-Bera (JB):          1728615.895
Skew:                           3.635   Prob(JB):                         0.00
Kurtosis:                      51.442   Cond. No.                     2.68e+17
==============================================================================

Notes:
[1] R² is computed without centering (uncentered) since the model does not contain a constant.
[2] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[3] The smallest eigenvalue is 2.43e-21. This might indicate that there are
strong multicollinearity problems or that the design matrix is singular.
"""

In [53]:
from sklearn.metrics import mean_squared_error, r2_score

# Compute R square score
r2_train = r2_score(y_train, y_train_pred)
r2_test = r2_score(y_test, y_test_pred)

# Compute MSE
mse_train = mean_squared_error(y_train_pred, y_train)
mse_test = mean_squared_error(y_test_pred, y_test)

df_scores = pd.DataFrame({'Train': [r2_train, mse_train], 'Test': [r2_test, mse_test]}, index=['R square', 'MSE'])
df_scores['Difference'] = df_scores['Train']-df_scores['Test']
df_scores

                 Train          Test    Difference
R square  7.007446e-01  7.026560e-01 -1.911345e-03
MSE       3.909730e+10  4.495149e+10 -5.854193e+09